version: '3.4'
services:
  core:
    build: .
    image: topazdb/core  
    ports:
      - "80:80"
  
  gui:
    build: 
      context: ./gui
      target: development
    image: topazdb/gui
    volumes:
      - ./gui:/app
    command: npm start -- --watch
  
  db:
    build: ./server
    image: topazdb/server
    environment:
      - MARIADB_DATABASE=${TOPAZ_DATABASE}
      - MARIADB_ROOT_PASSWORD=${TOPAZ_PASSWORD}
  
  api:
    build: 
      context: ./api
      target: development
    volumes:
      - ./api/src:/app
      - /var/run/topazdb:/data
    image: topazdb/api
    environment:
      - TOPAZ_HOST=db
      - TOPAZ_USER
      - TOPAZ_PASSWORD
      - TOPAZ_DATABASE
