version: '3.4'
services:
  core:
    build: .
    image: topazdb/core
    depends_on:
      - gui
    ports:
      - "80:80"
  
  gui:
    build: 
      context: ./gui
      target: development
    image: topazdb/gui
    depends_on:
      - api
    volumes:
      - ./gui:/app
    command: npm start -- --watch
    environment:
      - TOPAZ_OKTA_DOMAIN
      - TOPAZ_OKTA_CLIENTID
      - TOPAZ_OKTA_AUTHSERV
      - TOPAZ_OKTA_REDIRECTURI

  db:
    build: ./server
    image: topazdb/server
    volumes:
      - data-store:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${TOPAZ_DATABASE}
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_USER=${TOPAZ_USER}
      - MARIADB_PASSWORD=${TOPAZ_PASSWORD}
  
  api:
    build: 
      context: ./api
      target: development
    volumes:
      - ./api/src:/app
      - /run/topazdb:/data
    image: topazdb/api
    depends_on:
      - db
    environment:
      - TOPAZ_BASEURL
      - TOPAZ_HOST=db
      - TOPAZ_USER
      - TOPAZ_PASSWORD
      - TOPAZ_DATABASE
      - TOPAZ_OKTA_AUTHSERV
      - TOPAZ_OKTA_DOMAIN
      - TOPAZ_OKTA_CLIENTID
      - TOPAZ_OKTA_CLIENTSECRET

volumes:
  data-store: