version: '3'
services:
  core:
    image: topazdb/core
    restart: unless-stopped
    depends_on:
      - gui 
    ports:
      - "80:80"
  
  gui:
    image: topazdb/gui
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - backend
    environment:
      - TOPAZ_OKTA_DOMAIN
      - TOPAZ_OKTA_CLIENTID
      - TOPAZ_OKTA_AUTHSERV
      - TOPAZ_OKTA_REDIRECTURI
  
  db:
    image: topazdb/server
    restart: unless-stopped
    volumes:
      - data-store:/var/lib/mysql
    networks:
      - backend
    environment:
      - MARIADB_DATABASE=${TOPAZ_DATABASE}
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_USER=${TOPAZ_USER}
      - MARIADB_PASSWORD=${TOPAZ_PASSWORD}

  api:
    image: topazdb/api
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - /run/topazdb:/data
    environment:
      - TOPAZ_BASEURL
      - TOPAZ_HOST=db
      - TOPAZ_USER
      - TOPAZ_PASSWORD
      - TOPAZ_DATABASE
      - TOPAZ_OKTA_AUTHSERV
      - TOPAZ_OKTA_DOMAIN
      - TOPAZ_OKTA_CLIENTID
      - TOPAZ_OKTA_CLIENTSECRET

  updater:
    image: pyouroboros/ouroboros
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - INTERVAL=300
      - CLEANUP=true
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - TZ=America/Chicago
      - MONITOR="topazdb/core topazdb/server topazdb/api topazdb/gui"

volumes:
  data-store:

networks:
  backend: